export const top50Data = [
  {"rank": 1, "model": "claude-fable-5", "company": "Anthropic", "score": "1509 ±6"},
  {"rank": 2, "model": "claude-opus-4-6-thinking", "company": "Anthropic", "score": "1505 ±4"},
  {"rank": 3, "model": "claude-opus-4-7-thinking", "company": "Anthropic", "score": "1502 ±4"},
  {"rank": 4, "model": "claude-opus-4-6", "company": "Anthropic", "score": "1497 ±4"},
  {"rank": 5, "model": "qwen3.8-max", "company": "阿里", "score": "1496 ±10"},
  {"rank": 6, "model": "claude-opus-4-7", "company": "Anthropic", "score": "1492 ±4"},
  {"rank": 7, "model": "claude-opus-5-high", "company": "Anthropic", "score": "1492 ±6"},
  {"rank": 8, "model": "claude-opus-5-max", "company": "Anthropic", "score": "1490 ±9"},
  {"rank": 9, "model": "muse-spark-1.1", "company": "Meta", "score": "1490 ±6"},
  {"rank": 10, "model": "muse-spark", "company": "Meta", "score": "1488 ±6"},
  {"rank": 11, "model": "gemini-3-pro", "company": "Google", "score": "1486 ±4"},
  {"rank": 12, "model": "gemini-3.1-pro-preview", "company": "Google", "score": "1485 ±3"},
  {"rank": 13, "model": "kimi-k3-max", "company": "Moonshot", "score": "1485 ±10"},
  {"rank": 14, "model": "claude-opus-4-8-thinking", "company": "Anthropic", "score": "1484 ±5"},
  {"rank": 15, "model": "gpt-5.6-sol-xhigh", "company": "OpenAI", "score": "1483 ±6"},
  {"rank": 16, "model": "gemini-3.6-flash", "company": "Google", "score": "1483 ±7"},
  {"rank": 17, "model": "gpt-5.5-high", "company": "OpenAI", "score": "1482 ±4"},
  {"rank": 18, "model": "gpt-5.4-high", "company": "OpenAI", "score": "1477 ±4"},
  {"rank": 19, "model": "gemini-3.6-flash-high", "company": "Google", "score": "1476 ±7"},
  {"rank": 20, "model": "gpt-5.5", "company": "OpenAI", "score": "1476 ±4"},
  {"rank": 21, "model": "gpt-5.2-chat-latest-20260210", "company": "OpenAI", "score": "1476 ±4"},
  {"rank": 22, "model": "gemini-3.6-flash-lite", "company": "Google", "score": "1475 ±6"},
  {"rank": 23, "model": "qwen3.7-max-preview", "company": "阿里", "score": "1475 ±10"},
  {"rank": 24, "model": "claude-opus-4-8", "company": "Anthropic", "score": "1475 ±5"},
  {"rank": 25, "model": "grok-4.20-beta1", "company": "xAI", "score": "1474 ±5"},
  {"rank": 26, "model": "gemini-3.6-flash-medium", "company": "Google", "score": "1474 ±5"},
  {"rank": 27, "model": "gpt-5.5-instant", "company": "OpenAI", "score": "1473 ±5"},
  {"rank": 28, "model": "gemini-3-flash", "company": "Google", "score": "1473 ±4"},
  {"rank": 29, "model": "claude-opus-4-5-20251101-thinking-32k", "company": "Anthropic", "score": "1473 ±4"},
  {"rank": 30, "model": "grok-4.20-beta-0309-reasoning", "company": "xAI", "score": "1472 ±4"},
  {"rank": 31, "model": "claude-sonnet-4-6", "company": "Anthropic", "score": "1472 ±4"},
  {"rank": 32, "model": "grok-4.20-multi-agent-beta-0309", "company": "xAI", "score": "1471 ±4"},
  {"rank": 33, "model": "glm-5.2-max", "company": "Z.ai", "score": "1469 ±5"},
  {"rank": 34, "model": "claude-opus-4-5-20251101", "company": "Anthropic", "score": "1469 ±3"},
  {"rank": 35, "model": "grok-4.5", "company": "xAI", "score": "1469 ±6"},
  {"rank": 36, "model": "glm-5.1", "company": "Z.ai", "score": "1469 ±4"},
  {"rank": 37, "model": "gpt-5.6-terra-xhigh", "company": "OpenAI", "score": "1468 ±6"},
  {"rank": 38, "model": "ernie-5.1", "company": "百度", "score": "1468 ±5"},
  {"rank": 39, "model": "grok-4.1-thinking", "company": "xAI", "score": "1466 ±3"},
  {"rank": 40, "model": "mimo-v2.5-pro", "company": "小米", "score": "1466 ±4"},
  {"rank": 41, "model": "gpt-5.4", "company": "OpenAI", "score": "1465 ±4"},
  {"rank": 42, "model": "qwen3.5-max-preview", "company": "阿里", "score": "1465 ±5"},
  {"rank": 43, "model": "claude-sonnet-5-high", "company": "Anthropic", "score": "1462 ±6"},
  {"rank": 44, "model": "kimi-k2.6", "company": "Moonshot", "score": "1461 ±5"},
  {"rank": 45, "model": "qwen3.6-max-preview", "company": "阿里", "score": "1460 ±8"},
  {"rank": 46, "model": "grok-4.1", "company": "xAI", "score": "1459 ±3"},
  {"rank": 47, "model": "qwen3.7-plus", "company": "阿里", "score": "1459 ±5"},
  {"rank": 48, "model": "gemini-3-flash (thinking-minimal)", "company": "Google", "score": "1459 ±3"},
  {"rank": 49, "model": "deepseek-v4-pro", "company": "DeepSeek", "score": "1458 ±4"},
  {"rank": 50, "model": "glm-5", "company": "Z.ai", "score": "1457 ±4"}
];

export const pricingData = [
  {"company": "OpenAI", "model": "GPT-5.6 Sol", "input": "¥36.0", "output": "¥216.0", "note": "旗舰深度推理模型"},
  {"company": "OpenAI", "model": "GPT-5.6 Terra", "input": "¥14.4", "output": "¥86.4", "note": "面向企业日常高并发任务"},
  {"company": "OpenAI", "model": "GPT-5.6 Luna", "input": "¥1.44", "output": "¥8.64", "note": "7月降价80%，主打极速轻量应用"},
  {"company": "Anthropic", "model": "Claude Fable 5", "input": "¥72.0", "output": "¥360.0", "note": "新一代长效 Agent 顶配模型"},
  {"company": "Anthropic", "model": "Claude Opus 5", "input": "¥36.0", "output": "¥180.0", "note": "复杂代码与企业级分析"},
  {"company": "Anthropic", "model": "Claude Sonnet 5", "input": "¥14.4", "output": "¥72.0", "note": "主力性价比模型"},
  {"company": "Google", "model": "Gemini 3.6 Flash", "input": "¥10.8", "output": "¥64.8", "note": "高速低延迟模型"},
  {"company": "Google", "model": "Gemini 3-Pro 系列", "input": "~¥25.2", "output": "~¥108.0", "note": "高级多模态分析与生成"},
  {"company": "xAI", "model": "Grok 4.20", "input": "¥18.7", "output": "¥56.1", "note": "2M 超长上下文，支持实时数据"},
  {"company": "xAI", "model": "Grok 4.5", "input": "¥14.4", "output": "¥43.2", "note": "基础版高速模型"},
  {"company": "阿里", "model": "Qwen3.8-Max", "input": "¥20.0", "output": "¥60.0", "note": "阿里云百炼平台计费，支持模型降价"},
  {"company": "阿里", "model": "Qwen 3.7", "input": "¥12.0", "output": "¥36.0", "note": "上一代模型，极高性价比"},
  {"company": "阿里", "model": "Qwen3.5-Plus", "input": "¥0.8", "output": "¥2.0", "note": "高频调用性价比极高"},
  {"company": "Moonshot", "model": "Kimi K3-Max", "input": "¥20.0", "output": "¥100.0", "note": "缓存命中时输入可降至 ¥2.0/百万"},
  {"company": "Z.ai", "model": "GLM-5.2-Max", "input": "~¥4.3", "output": "~¥10.8", "note": "国内模型 API 的“性价比屠夫”之一"},
  {"company": "DeepSeek", "model": "DeepSeek-V4-Pro", "input": "¥12.5", "output": "¥25.0", "note": "默认开启思维链（思考 Token 按输出计）"},
  {"company": "DeepSeek", "model": "DeepSeek-V4-Flash", "input": "¥1.0", "output": "¥2.0", "note": "缓存命中时输入仅需 ¥0.02/百万"},
  {"company": "百度", "model": "Ernie-5.1 (旗舰)", "input": "¥30.0", "output": "¥90.0", "note": "百度千帆大模型平台旗舰定价"},
  {"company": "字节跳动", "model": "Doubao-Seed-2.0-Pro", "input": "¥0.8", "output": "¥2.0", "note": "延续火山引擎的“击穿底价”策略"},
  {"company": "小米", "model": "MiMo-V2.5-Pro", "input": "¥15.0", "output": "¥45.0", "note": "主打端云协同生态应用"},
  {"company": "腾讯", "model": "Hunyuan 3 (混元)", "input": "¥30.0", "output": "¥100.0", "note": "面向政企及高复杂应用场景"},
  {"company": "MiniMax", "model": "abab 7.5", "input": "¥10.0", "output": "¥30.0", "note": "极致语音多模态及万字长文解析"},
  {"company": "Z.ai", "model": "GLM-5.2-Flash", "input": "¥0.1", "output": "¥0.5", "note": "零延迟边缘设备首选模型"},
  {"company": "Moonshot", "model": "Kimi K3-Pro", "input": "¥8.0", "output": "¥30.0", "note": "日常高速交互与代码生成"},
  {"company": "Meta", "model": "Muse Spark", "input": "¥9.0", "output": "¥30.6", "note": "Meta 最新闭源主力前沿模型"}
];

export const plansData = [
  {"company": "OpenAI", "plan": "ChatGPT Plus", "price": "¥144 /月 ($20)", "users": "基础个人用户 (标准额度)；解锁 GPT-5.6/Terra"},
  {"company": "OpenAI", "plan": "ChatGPT Team", "price": "¥180 /席/月 ($25)", "users": "协作团队 (Plus额度的2倍)；不用于模型训练"},
  {"company": "OpenAI", "plan": "ChatGPT Pro", "price": "¥1,440 /月 ($200)", "users": "极客开发者 (Plus额度的10倍)；高并发推理模式"},
  {"company": "OpenAI", "plan": "ChatGPT Max", "price": "¥2,880 /月 ($400)", "users": "顶级开发者 (Plus额度的20倍)；独占 Sol 超级推理"},
  {"company": "Anthropic", "plan": "Claude Pro", "price": "¥144 /月 ($20)", "users": "个人主力 (标准额度)；解锁 Opus 5、Sonnet 5"},
  {"company": "Anthropic", "plan": "Claude Max 5x", "price": "¥720 /月 ($100)", "users": "高阶玩家 (Pro额度的5倍)；解锁顶级 Fable 5"},
  {"company": "Anthropic", "plan": "Claude Max 20x", "price": "¥1,440 /月 ($200)", "users": "极客玩家 (Pro额度的20倍)；解锁顶级 Fable 5"},
  {"company": "Anthropic", "plan": "Claude Team Premium", "price": "¥900 /席/月 ($125)", "users": "研发工程团队 (Pro额度的6倍)；深度集成 Code"},
  {"company": "Google", "plan": "Google One AI Premium", "price": "¥144 /月 ($20)", "users": "个人用户 (标准额度)；无缝集成 Gemini 3-Pro"},
  {"company": "Google", "plan": "Google AI Studio Pro", "price": "¥720 /月 ($100)", "users": "专业开发者 (Premium额度的5倍)；不限量 Flash"},
  {"company": "xAI", "plan": "X Premium", "price": "¥58 /月 ($8)", "users": "Twitter基础会员 (标准额度)；解锁 Grok 4.5"},
  {"company": "xAI", "plan": "X Premium+", "price": "¥115 /月 ($16)", "users": "重度用户 (Premium额度的3倍)；解锁 Grok 4.20"},
  {"company": "阿里", "plan": "百炼平台 Lite 版", "price": "¥39 /月", "users": "入门开发者 (标准额度)；含基础 Qwen 抵扣包"},
  {"company": "阿里", "plan": "百炼平台 Standard版", "price": "¥139 /月", "users": "中小型企业 (Lite额度的4倍)；专属算力调配"},
  {"company": "阿里", "plan": "百炼平台 Pro 版", "price": "¥499 /月", "users": "大企业应用 (Lite额度的15倍)；含高级 Max 系列"},
  {"company": "Moonshot", "plan": "Kimi Plus", "price": "¥39 /月", "users": "基础用户 (标准额度)；高峰期优先调用保障"},
  {"company": "Moonshot", "plan": "Kimi Pro", "price": "¥149 /月", "users": "深度创作者 (Plus额度的5倍)；长文深度推理模式"},
  {"company": "MiniMax", "plan": "海螺 AI Plus", "price": "¥30 /月", "users": "基础用户 (标准额度)；全功能无限制访问"},
  {"company": "MiniMax", "plan": "海螺 AI Pro", "price": "¥120 /月", "users": "极客用户 (Plus额度的4倍)；专属复杂 Agent 任务池"},
  {"company": "Z.ai", "plan": "智谱网页 VIP", "price": "¥79 /月", "users": "基础用户 (标准额度)；长文档与 AI 绘画加速"},
  {"company": "Z.ai", "plan": "智谱网页 SVIP", "price": "¥229 /月", "users": "专业用户 (VIP额度的3倍)；数据分析与专属智能体"},
  {"company": "Z.ai", "plan": "GLM Coding Lite", "price": "¥118 /月 ($18)", "users": "入门开发者 (标准额度)；专用编程模型推理"},
  {"company": "Z.ai", "plan": "GLM Coding Pro", "price": "¥590 /月", "users": "极客开发者 (Lite额度的5倍)；深度集成开发工具"},
  {"company": "Z.ai", "plan": "GLM Coding Max", "price": "¥2,360 /月", "users": "顶级开发者 (Lite额度的20倍)；高并发专有算力"},
  {"company": "Meta", "plan": "Meta One Plus", "price": "¥58 /月 ($7.99)", "users": "基础个人用户 (标准额度)；高算力推理与生成"},
  {"company": "Meta", "plan": "Meta One Premium", "price": "¥144 /月 ($19.99)", "users": "高级用户 (Plus额度的3倍)；解锁深度思维模式 (Thinking)"},
  {"company": "DeepSeek", "plan": "/（纯后付费模式）", "price": "无固定月租", "users": "完全“Pay-as-you-go”计费，无上限 (按量计算)"}
];
